// ------------------------------------
// Constants
// ------------------------------------
export const PASSPORT_FETCH_ACCESSTOKEN_BEGIN     = 'PASSPORT_FETCH_ACCESSTOKEN_BEGIN'
export const PASSPORT_FETCH_ACCESSTOKEN_FAILURE   = 'PASSPORT_FETCH_ACCESSTOKEN_FAILURE'
export const PASSPORT_FETCH_ACCESSTOKEN_SUCCESS   = 'PASSPORT_FETCH_ACCESSTOKEN_SUCCESS'

export const PASSPORT_FETCH_LOGIN_BEGIN           = 'PASSPORT_FETCH_LOGIN_BEGIN'
export const PASSPORT_FETCH_LOGIN_FAILURE         = 'PASSPORT_FETCH_LOGIN_FAILURE'
export const PASSPORT_FETCH_LOGIN_SUCCESS         = 'PASSPORT_FETCH_LOGIN_SUCCESS'