// ------------------------------------
// Constants
// ------------------------------------
export const ADMINSGROUP_FETCH_LIST_BEGIN     = 'ADMINSGROUP_FETCH_LIST_BEGIN'
export const ADMINSGROUP_FETCH_LIST_FAILURE   = 'ADMINSGROUP_FETCH_LIST_FAILURE'
export const ADMINSGROUP_FETCH_LIST_SUCCESS   = 'ADMINSGROUP_FETCH_LIST_SUCCESS'

export const ADMINSGROUP_FETCH_FLAG_BEGIN     = 'ADMINSGROUP_FETCH_FLAG_BEGIN'
export const ADMINSGROUP_FETCH_FLAG_FAILURE   = 'ADMINSGROUP_FETCH_FLAG_FAILURE'
export const ADMINSGROUP_FETCH_FLAG_SUCCESS   = 'ADMINSGROUP_FETCH_FLAG_SUCCESS'